browserstack/a11y-engine-axe-core

lib/checks/forms/autocomplete-a11y-evaluate.js, lib/checks/forms/autocomplete-valid.json, lib/rules/autocomplete-a11y-matches.js, lib/rules/autocomplete-matches.js, lib/rules/autocomplete-valid.json, test/rule-matches/autocomplete-matches.js
=> Autocomplete attribute valid

lib/commons/a11yCommons/index.js, lib/commons/index.js
=> Added a11y commons

lib/checks/color/link-in-text-block-evaluate.js
=> Added condition only in a11y-engine rule

build/tasks/validate.js
=> chore: updated tags in validate js file to include advanced tag

lib/checks/forms/autocomplete-a11y-evaluate.js
JIRA : https://browserstack.atlassian.net/browse/AXE-197
=> fix: (AXE-197) excluded select and textarea components

build/tasks/validate.js
=> feat: add a new category: images

package-lock.json
Merged dependabot brace upgrade from 3.0.2 to 3.0.3
Closes: https://github.com/browserstack/a11y-engine-axe-core/commit/5a6508ed18410bfb4c97fd19ff834012faa256f4
=> Release 2.2.1

lib/rules/heading-order.json
=> Updated the tags

lib/checks/navigation/heading-order.json, lib/rules/heading-order.json
=> Release 2.3.0

lib/core/public/load.js, lib/core/public/run-rules.js, lib/core/utils/collect-results-from-frames.js, lib/core/utils/merge-errors.js, lib/core/utils/merge-results.js
=> Merge release-2.3.1 into release-2.4.0

lib/core/public/run-rules.js
=> Iframe fix for automate

package-lock.json
=> Release 2.5.0

.github/workflows/test.yml
=> Release 2.6.0

lib/core/public/load.js, lib/core/public/run-rules.js, lib/core/utils/merge-results.js
Reverts browserstack/a11y-engine-axe-core#103
=> Revert "Fix: AXE-570 Fixed a11yEngineErrors being accessed on undefined"

lib/core/public/load.js, lib/core/public/run-rules.js, lib/core/utils/merge-results.js
Reverts browserstack/a11y-engine-axe-core#104
=> Revert "Revert "Fix: AXE-570 Fixed a11yEngineErrors being accessed on undefined""

build/tasks/esbuild.js
=> added changes for build process

lib/core/utils/get-selector.js
=> Release 3.2.0

lib/core/utils/aggregate-checks.js
=> chore: added severity to passes result also

lib/core/utils/aggregate-checks.js
https://browserstack.atlassian.net/wiki/spaces/ENG/pages/4459036728/3.2.1
Closes:
=> Release 3.2.1

lib/commons/dom/get-overflow-hidden-ancestors.js, lib/core/base/rule.js
=> Fix: Revert back to original get overflown hidden ancestors else case

.eslintrc.js, .github/workflows/test.yml, lib/checks/color/link-in-text-block-evaluate.js, lib/commons/a11y-engine-index.js
=> fix: PR check

lib/checks/color/link-in-text-block-evaluate.js
=> Fix: AXE-789 - distinguishable-link standalone case

lib/rules/autocomplete-a11y-matches.js
=> fix: autocomplete enhancement fixes

lib/rules/label-content-name-mismatch.json
=> fix: reverting label-content

lib/rules/label-content-name-mismatch.json
=> fix: Enabled a11y-engine Type A rule

build/tasks/validate.js
=> fix: added new tag

lib/commons/dom/get-visible-child-text-rect.js, lib/commons/dom/index.js, lib/core/utils/dq-element.js, lib/rules/autocomplete-valid.json
=> Release 5.1.0

lib/commons/color/get-foreground-color.js
=> Release 5.1.1

lib/commons/dom/get-overflow-hidden-ancestors.js
=> Updated getOverflowHiddenAncestors
